---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./external-secrets/ks.yaml
  - ./eso-rb.yaml
  # - ./forgejo/ks.yaml
  - ./harbor/ks.yaml
  - ./keycloak/ks.yaml
  - ./rabbitmq-operator/ks.yaml
