---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.16.0
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
      interval: 10m
  install:
    timeout: 30m
    replace: true
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  driftDetection:
    mode: enabled
  maxHistory: 3
  values:
    operatorNamespace: rook
    toolbox:
      enabled: true
    monitoring:
      enabled: true
      createPrometheusRules: true
    cephClusterSpec:
      dataDirHostPath: /var/lib/rook
      network:
        provider: host
      mon:
        count: 1
      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "1"
