# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:wWCLJtnqnf7vFaOEKjkPA2zGb4/oNw6I5RcWQUwy/kw=,iv:XnwoTm6JMHjsY34OA/dNmS+PltNwQqU9iW55C7l+Vo0=,tag:DWW477p2+KvYU/k8RxQFjw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1du3d09j5gl5u7qcafgjk2u7nej34cvtldfvpt2s67nhvrwzezpfqxqpwju
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYmc4TWEyR1hSdUx2YTRM
        SGJNWWEzdE14eGJrZUQ0eXlUNEs3c2xkMzBVClZkM3RudFJRaE53MXFQeWt6dUFl
        bXcwYStUcWdEbEJZZDRvOTJYM3MyQkkKLS0tIExja2UxWlBaaGdXM0cwQU1XR1NL
        NVlaa2dkWUp4QkxxdVdiZVdGQ3lEbE0KXP7kxlSVORVcryIJgh/6ZKPUGatbRMti
        jqUg9frlZuaSaVtgAy4LZYhwpCeg8HVoGrG+NCEOmZkWEUfkGchsBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-12T11:30:50Z"
  mac: ENC[AES256_GCM,data:UoevMufRy4kUyd3V18koZja2qf51sdYPmN9pfa9dJBMq2DIpuqfH7I4Saz8rEUbcnS41ngLA6G6hommR/1xWX/WUSGCr2uwVn5xQweZOGFtoA5Fd1mlXJAl07Na1YR9l5+doAehPcnZzjOtx3FDJU4O4tkSewlKDatwfoBcKeng=,iv:4/MXEId05teTXKveNZEzrF1XhaKqw5/4h9UL+/ciOso=,tag:quSSMLgFr5Cz08e6FhePIw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
