---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./ceph-csi.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./grafana.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./traefik.yaml
