---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stakater
  namespace: flux-system
spec:
  type: oci
  interval: 5m
  # TODO migrer vers harbor
  url: oci://ghcr.io/stakater/charts
