# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: milim-cert
spec:
  secretName: milim-prod-tls-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod
  commonName: "milim.samoth.eu"
  dnsNames:
    - "milim.samoth.eu"
    - "*.milim.samoth.eu"
