---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ceph-csi-rbd
spec:
  interval: 30m
  chart:
    spec:
      chart: ceph-csi-rbd
      version: 3.13.1
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    csiConfig:
      - clusterID: 8452515a-f5d3-45ac-b428-cb6d56e36a03
        monitors:
          - 192.168.0.5
          - 192.168.0.7
          - 192.168.0.8

    logLevel: 2

    selinuxMount: false

    storageClass:
      create: true
      name: csi-rbd-sc
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      clusterID: 8452515a-f5d3-45ac-b428-cb6d56e36a03
      pool: cephpool_milim

    provisioner:
      name: provisioner
      replicaCount: 2

    secret:
      # Specifies whether the secret should be created
      create: false
      name: csi-rbd-secret
