# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname rabbitmq-cluster-operator
  namespace: flux-system
spec:
  targetNamespace: infrastructure
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: ./kubernetes/apps/infrastructure/rabbitmq-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
