---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: 1.16.1
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      interval: 5m
  values:
    externalURL: https://harbor.milim.samoth.eu
    expose:
      ingress:
        hosts:
          core: harbor.milim.samoth.eu
        className: traefik-internal
      # we do not want harbor internal cert
      tls:
        enabled: false
    database:
      type: external
      external:
        host: hippo-ha-ha.database.svc
        username: harbor
        coreDatabase: harbor
        existingSecret: harbor-database-secret
        sslmode: require
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    trivy:
      resources:
        requests:
          cpu: 10m
          memory: 256Mi
    persistence:
      persistentVolumeClaim:
        registry:
          size: 20Gi
