---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: 1.17.0
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      interval: 5m
  values:
    imagePullPolicy: Always
    externalURL: https://harbor.milim.samoth.eu
    expose:
      ingress:
        hosts:
          core: harbor.milim.samoth.eu
        className: traefik-internal
      # we do not want harbor internal cert
      tls:
        enabled: false
    database:
      type: external
      external:
        host: elephant-primary.database.svc
        username: harbor
        coreDatabase: harbor
        existingSecret: harbor-database-secret
        sslmode: require
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    trivy:
      resources:
        requests:
          cpu: 10m
          memory: 256Mi
    core:
      replicas: 2
    registry:
      replicas: 2
    persistence:
      persistentVolumeClaim:
        registry:
          existingClaim: lh-harbor-registry
          accessMode: ReadWriteMany
          size: 20Gi
        jobservice:
          jobLog:
            storageClass: longhorn
            accessMode: ReadWriteMany
        redis:
          storageClass: longhorn
        trivy:
          storageClass: longhorn
