---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./prometheus-operator-crds/ks.yaml
  # TODO à réactiver quand ceph sera ok
  # - ./kube-prometheus-stack/ks.yaml
