apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:j/3SkCIh6i3Ju4IobTG2/s1Jy2yDik9BqLewmm5gpRon0tURhONqSbxeuQ9+JMUiJw4ubh0n2AEGeG7PYk3dkBwXQijFaY+vAYXKeISSFg2F,iv:K48KVmKDv9GnZTOgvk/8JLkBmexSy7yG9pqnRYZiiUQ=,tag:iahZIvFF8mjqVKG926NXOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1du3d09j5gl5u7qcafgjk2u7nej34cvtldfvpt2s67nhvrwzezpfqxqpwju
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQzJOUjNyVG8zNTJ6cVdv
            UEpwMjlZWk0vOU9GZlBTVGZ6WDdXQU1oR2prCnVGQUZuMk81MDdpRlNuUUc2a0FX
            d2F2aHRnZUY2T0hEN1FNWDF2NDFvTzQKLS0tIG8wd1dWcDJ0ZENhWi9wVzg5RktH
            a3dOWlNMUkJhemRlKzlReG9KeXFVRE0KfkvyfkJwAreylp0lsSLiX0wNZ4HigdZS
            vKJqdWo4a62M4+mIarTGaL00hZgoN1eS2obQZoG5t06M5xjYJJXK+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T10:18:29Z"
    mac: ENC[AES256_GCM,data:TTiV1PcrKiKBRmDyoN2LjkQvLYd1L989sLGqCaUlDCTWgeJhVpiiAte6J1zP0XtHPGZ+0QK+kgNsYYU3dsjuCQln9m93AcBHvpdHzSK5crMWCVDIYvFKaNhdq7L/rsmhre/QHAAwjd2hiePuPZGaNyFdxULe/Hg0Gzv0Tf35S44=,iv:Ka1m+nIM33ROc5yr6xH5lM2tLVxRxoWD7LnaAcGALuE=,tag:ESGgeirMl+U4Oo9A1qSRzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
