apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:AmYOarue0k8dYQoc0PFLgkKUTA1EpVRmUEl0aY0HeisNFSB+oHP7VbO6Nf/jKyzYYkGU1DdjDbeILxQzVwdEt5vUvWM8DUl7GCjNphq6Zwpa,iv:6rYALW5iaF9ATTNlFVTqp1PCkSWOjagePijJpxDN2Tw=,tag:b7VwUro4/ynoPPhmx1K77A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1du3d09j5gl5u7qcafgjk2u7nej34cvtldfvpt2s67nhvrwzezpfqxqpwju
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlS0tHa2FSU2J3a242NlBv
            ZkRxcnlDMmJSUkdSaXJNYmZYRVlxSXJFelNNCjE0Z2ZBM1k5OUxnRXVYSFRjVHd5
            TXgwV1playt4ampDQWlzMElpazg5NU0KLS0tIFdkc3FDekxjWEE3V1hHRjZPZkw0
            OVRtV1pveUlhR3Q4bEtlcDhVSSs2bkEKmoUMI9P6DG9GBbleuuh7UbyeptnwSC3m
            lIW9jK+4tqGlrEp6+fqKgKmwu+eZNow9VE5fnHguTC2Sn4C9M2vUng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T20:40:38Z"
    mac: ENC[AES256_GCM,data:hUbITWmMujnOElGuGnQChJckdIadZ5Hd7gPkVbaJ6ZCeQDkjr3sEt6N5YHUToYsXbfLjJnq5Sju8ysQ09SXwrzD0IPU0Rv5uEGDYiiwjloUbnGWhL67iWD+TWAvZeHDF21kqLcB2srnamLFUxrcRUuHqYxREn+8C6ZYpTKZLQcE=,iv:MaypBDpUJIJc4Ew58xUPRd5h0pykuVt8hDjPzRGl9H4=,tag:2xqjqEA3JRJ5pqn/QqSDHg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
