---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: &name elephant
spec:
  dataSource:
    pgbackrest:
      stanza: db
      configuration:
        - secret:
            name: hippo-ha-secret
      global:
        repo1-s3-uri-style: path
        repo1-path: /pgbackrest/postgres-operator/milim/repo1
        repo1-retention-full: "14"
        repo1-retention-full-type: count
      repo:
        name: repo1
        s3:
          bucket: crunchy-postgres-backups
          endpoint: https://truenas.samoth.eu:9000
          region: us-east-1

  postgresVersion: 17

  metadata:
    labels:
      crunchy-userinit.ramblurr.github.com/enabled: "true"
      crunchy-userinit.ramblurr.github.com/superuser: postgres

  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        parameters:
          max_wal_size: 5GB
          synchronous_commit: 'on'
        pg_hba:
          - hostnossl all all 127.0.0.1/8 md5 # port forwarding without ssl
          - hostssl all all all md5


  instances:
    - name: elephant
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        storageClassName: longhorn
        resources:
          requests:
            storage: 40Gi
      resources:
        requests:
          cpu: 10m
          memory: 64M
        limits:
          memory: 1024M

  users:
    # Superuser
    - name: postgres
      databases:
        - postgres
      options: SUPERUSER
      password: &password
        type: AlphaNumeric
    # Applications
    - name: harbor
      databases:
        - harbor
      password: *password
    - name: movtrack6
      databases:
        - movtrack6
      password: *password
    - name: rsscachego
      databases:
        - rsscachego
      password: *password
    - name: forgejo
      databases:
        - forgejo
      password: *password
    - name: keycloak
      databases:
        - keycloak
      password: *password
    - name: woodpecker
      databases:
        - woodpecker
      password: *password

  monitoring:
    pgmonitor:
      exporter:
        resources:
          requests:
            cpu: 10m
            memory: 64M
          limits:
            memory: 512M

  backups:
    pgbackrest:
      manual:
        repoName: repo1
        options:
         - --type=full
      configuration:
        - secret:
            name: hippo-ha-secret
      global:
        repo1-s3-uri-style: path
        repo1-path: /pgbackrest/postgres-operator/milim/repo1
        repo1-retention-full: "14"
        repo1-retention-full-type: count
      repos:
        - name: repo1
          s3:
            bucket: crunchy-postgres-backups
            endpoint: https://truenas.samoth.eu:9000
            region: us-east-1
          schedules:
            full: "0 1 * * 0" # Sunday at 01:00
            differential: "0 */3 * * 1-6" # Mon-Sat at 01:00
