apiVersion: v1
kind: Secret
metadata:
  name: ips-harbor-milim
  namespace: app
data:
  .dockerconfigjson: ENC[AES256_GCM,data:WIGS2ks3OrKkRARp9HjCbMV+8FP28pBsOxVyvC4d4JNlzhOsNV/2kjQViMK1ZsfcVKI9htskOSouvxyqjfmRgiBZamnKdpSz68yyIdduNemCaE5guDv+u/kEAJ0HjSa2jlvXW0mzVIsAkxxmAJFf8hesu79o1Lb7CURSjcmEgmzBFv1YthRRNn2tY4mxsx98r0h6CMl9Oj6uVi2tyzs1LYumze89SW73,iv:vg9y/+ggw5jpr5IZIpA9O6s8VKRIXYmbo1Kl5h6uEAc=,tag:9cW6esvDLKi2P/xNEhTNzw==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1du3d09j5gl5u7qcafgjk2u7nej34cvtldfvpt2s67nhvrwzezpfqxqpwju
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UFhyN3hubDB1RTZQVW4r
        KzBSK3BjZ1Y2bUNHN2VZUjhrb2JYOFdpYmxjCi80TGNPMk9UYTEzSXA5bTNPdWE1
        Qm8xckVOb09HT0dUQjJST1dyVkpwVTAKLS0tIE96V1Rtb3RYSmVUNjJTbkRHYjVu
        Umw2bEcxYWs4OS9OU2dhdGhBV0pPZU0KOVwtlIBTuumu4X8C/DP3uC1LrI9rzY79
        uPSaZHK5Cq3soFxHyo6gPi0j36NlqhSS6VU6Zb6B7B3R/4V/29bGsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-15T20:29:03Z"
  mac: ENC[AES256_GCM,data:E2x0ctfnuJzcF4r7uNwR8KVmIKGwBMUon7yF2gu4SjVLG1KsOoAcXwA/76z0bX2PZmy7lyx2ZbIGIZ7caXr+3P2GFCYyJqPc964DzpP7JP3jgEVrD/pzWwM20+/rv6PR46qeiYYqcu0pQ4tXzSCE4N19oceN9U2kPJMUxg/jPHU=,iv:iulYtVdLJuhgY3jOWuAhyLnr6eyo8zQPgeWho45jNBM=,tag:ef/wwZfhBWYnsO6jOQmJhQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
