---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: woodpecker-database-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-database
  target:
    name: woodpecker-database-secret
    creationPolicy: Owner
  data:
    - secretKey: WOODPECKER_DATABASE_DATASOURCE
      remoteRef:
        key: elephant-pguser-woodpecker
        property: uri
