---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecrets.yaml
  - ./woodpecker-server-secret.sops.yaml
  - ./woodpecker-common-secret.sops.yaml
  - ./helmrelease.yaml
