---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    namespaceOverride: storage
    networkPolicies:
      enabled: true
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 2
      defaultDataLocality: best-effort
      migratable: false
      backupTargetName: minio-truenas
    ingress:
      enabled: true
      ingressClassName: traefik-internal
      host: longhorn.milim.samoth.eu
    defaultSettings:
      replicaSoftAntiAffinity: true
      replicaAutoBalance: true
      # renovate should handle this
      upgradeChecker: false
      createDefaultDiskLabeledNodes: true
      defaultDataPath: /var/mnt/sdb/longhorn
      defaultReplicaCount: 2
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
      allowCollectingLonghornUsageMetrics: false
