---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname uptime-kuma
  namespace: flux-system
spec:
  targetNamespace: app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/apps/app/uptime-kuma/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
