---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: 0.14.4
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/external-secrets/external-secrets
    installCRDs: true
    extendedMetricLabels: true
    log:
      level: info
      timeEncoding: iso8601
    serviceMonitor:
      enabled: true
      interval: 1m
    certController:
      image:
        repository: ghcr.io/external-secrets/external-secrets
      serviceMonitor:
        enabled: true
        interval: 1m
      log:
        level: info
        timeEncoding: iso8601
    webhook:
      image:
        repository: ghcr.io/external-secrets/external-secrets
      serviceMonitor:
        enabled: true
        interval: 1m
      log:
        level: info
        timeEncoding: iso8601
