apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:KdlwyecxdY0qE35ANLtQEYqsZ5CZKoT3KvMr72AP6yQ=,iv:wVMaZjIkVgnqiu4+Lqgd3FAtINtb1vMLwBx5Qdw41Po=,tag:y3y92AiKTjVXwBP+iuGxeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1du3d09j5gl5u7qcafgjk2u7nej34cvtldfvpt2s67nhvrwzezpfqxqpwju
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWnVXYkd1ZWpjdGwyeVZN
            eXBsdTIyRnRTanhxUFZ0ZkVQa1UvazNMV1hZCnhudVZ2eE5mY04wd1NtVkl0VGU3
            Y0hiVE1BdXB6S1pLWExFbUUzOWFnRW8KLS0tIGVaNFlGSTQySUYrSEppUFg2ZDZY
            Vm1mR0dFa3NRTFA5eHVOTll5SlNhNnMKQqxELz6ZhTzSKoO/9uuICsEgRj+WnpcE
            rmhTQscbobmNscbqASxorylEuybCl3z+t1iz1v4pikin6/ZAtfR4bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-21T20:40:38Z"
    mac: ENC[AES256_GCM,data:6Ez1rtia4lfC92LCua5Pqv0wxeezZRbl+o+vhFHcvhWcd0rYYLNsH0D0Teh7GahW6iGZ/DscDO8WoODyuZHwouE0cN/F93qwJLIWan53V9RFu3Y/9fMKLAbRwjdTbz+b2dvt5a4FLVfCQJM5Baii1Ldu8+wUAnWll8+N/iZYNOA=,iv:zZkrg+gwucGpuN7WHlcgvvyut7ZIAAYnZF3RzaT6MEo=,tag:ukqnt5dQyQZHBWJLtMIvKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
