apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:QlI3NsfY+8PyqzoAsfEiPRtUS6Yu5OypJhKkyYf+qDs=,iv:1JzJhv7tJIM1LWT5jv3TrmeX5/zD/qf3tO/G7QBVZRw=,tag:migZF+r0tSb/4uKrecowbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1du3d09j5gl5u7qcafgjk2u7nej34cvtldfvpt2s67nhvrwzezpfqxqpwju
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOczdmZnA0bUY5Mkd2T1dP
            QkhPM2xwZGdrODdDNXQ2OWw4WEFuazh5V1RNCkxVZ2NTWWU3dENkcG9iSVV5VXVQ
            R0FCRnJPUWxER2FzaFcvbk1CTFo5dlUKLS0tIFFGV21hSFlzdFV6YWVUTnIyelht
            MnROQjRTSFpTWW9EaEFYUysvbmVyWWMKdC8v12+jeVuSFgGnPLNaVzuZTSUjtBmo
            KNH5M0eDBRRbhH0rpXUtWoXKxO6mePgPCc0UUMYa63ha7HCTxN2UMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T10:38:07Z"
    mac: ENC[AES256_GCM,data:HqoLdhRabHcFViEtKqhtBCNPifcpCrYTFg4G54Iop4TR5g3jzavXbkjbDDd3Us1L3vwsshgj/0f8LFafWbXXEWTAHhP3MD2Mde7Nc9fO5EZAaYhAb0yKi3614mNSXO7bmGbMaNBLeO99Nu5kQV5exoWap1ngMIoROg8jgGOPmpw=,iv:Pavg4f9mjh0XORmqRrKJR9aZEuAliPT9izUFj1FJc5E=,tag:WLQ/Dt9UuCRaM104jnN5bw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
