---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 35.2.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    deployment:
      replicas: 3
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik-internal
    globalArguments: []
    ports:
      web:
        # make sure to update the network policy accordingly
        port: 8000
      websecure:
        # make sure to update the network policy accordingly
        port: 8443
      gittcp:
        port: 2222
        exposedPort: 2222
        protocol: TCP
        expose:
          default: true
        tls:
          enabled: false
    service:
      annotations:
        "lbipam.cilium.io/ips": "192.168.1.30"
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: '{{ template "traefik.name" . }}'
                  app.kubernetes.io/instance: '{{ .Release.Name }}-{{ include "traefik.namespace" . }}'
              topologyKey: kubernetes.io/hostname
    priorityClassName: high-priority
