---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 33.2.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    deployment:
      replicas: 1
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik-internal
    globalArguments: []
    logs:
      general:
        level: "DEBUG"
      access:
        enabled: true
        addInternals: true
    service:
      annotations:
        "lbipam.cilium.io/ips": "192.168.1.30"
