---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-internal
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 34.0.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    deployment:
      replicas: 1
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik-internal
    globalArguments: []
    ports:
      web:
        # make sure to update the network policy accordingly
        port: 8000
      websecure:
        # make sure to update the network policy accordingly
        port: 8443
    service:
      annotations:
        "lbipam.cilium.io/ips": "192.168.1.30"
