apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: network-policy
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: traefik-internal-traefik-ingress
  ingress:
    - fromEntities:
      - cluster
      fromCIDR:
      - 192.168.1.1/32
      toPorts:
      - ports:
        - port: "80"
          protocol: "TCP"
        - port: "80"
          protocol: "UDP"
        - port: "443"
          protocol: "TCP"
        - port: "443"
          protocol: "UDP"
  egress:
    - toEntities:
      - ingress
