---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "e2e"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - kubernetes/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  configure:
    if: ${{ github.repository == 'onedr0p/cluster-template' }}
    name: configure
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config-files:
          - talos
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup mise
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install dependencies
        run: mise run deps

      - name: Run age task
        run: task template:generate-age-key

      - name: Run init task
        run: |
          task init
          cp ./.github/tests/config-${{ matrix.config-files }}.yaml ./config.yaml
          export TEMPLATE_AGE_PUBLIC_KEY=$(sed -n 's/# public key: //gp' age.key)
          envsubst < ./config.yaml > ./config.yaml.tmp && mv ./config.yaml.tmp ./config.yaml

      - name: Run configure task
        run: task configure --yes

      - name: Run cleanup task
        run: task template:tidy --yes
