---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./l2announcementpolicy.yaml
  - ./loadbalancerippool.yaml
  - ./filter-world-trafic.yaml
  - ./intercept-all-dns.yaml
