apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: pgo-network-policy
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: crunchy-userinit-controller
  ingress:
    # nothing allowed
    - {}
  egress:
    - toEndpoints:
      - matchLabels:
          postgres-operator.crunchydata.com/cluster: hippo-ha
    - toEntities:
      - kube-apiserver
